### ISSUE TITLE
Issue while launching the file

### ISSUE THREAD

**Issue by dineshrboson** [pietrocolombo/imu_from_ios_sensorlog#3]
Hi I see no data coming even after following the steps correctly. 
I had attached the images for reference.
![Screenshot from 2022-01-15 13-54-01](https://user-images.githubusercontent.com/77951479/149615162-19fcbcb5-2f57-452d-aabe-720ddc7e47e0.png)
![Screenshot from 2022-01-15 13-56-13](https://user-images.githubusercontent.com/77951479/149615171-b16bb011-b86b-43f1-9d62-57e1d505d5c9.png)
The same process when I tried to execute with python seems to be working for me

**Comment by dineshrboson** [comment]
![Uploading D88C1237-8B2C-4A24-802C-41293F0727E3.png…]()

**Comment by dineshrboson** [comment]
![50603DEB-F57D-4F1C-81CE-B8035F2016DC](https://user-images.githubusercontent.com/77951479/149615217-377d88fe-cd75-451a-b461-88e45df0263b.png)

**Comment by pietrocolombo** [comment]
Hi, try changing the port and putting 12000.

I get that error if I don't have the application open.

Another test you can do is connect to another wifi network and try there, maybe your router blocks some ports.

**Comment by dineshrboson** [comment]
hye I tried with multiple networks but nothing seems to be working for me
python code seems to be capturing the data.

![Screenshot from 2022-01-17 16-05-53](https://user-images.githubusercontent.com/77951479/149754064-175c4210-90cd-4c54-b146-8ebc5853558e.png)
![Screenshot from 2022-01-17 16-06-09](https://user-images.githubusercontent.com/77951479/149754075-55a259fe-93c5-41f1-aa20-fae480cc3032.png)

**Comment by dineshrboson** [comment]
I uninstalled and blocked laptop firewall as well and kept app open in mobile

**Comment by dineshrboson** [comment]
hye finally its working for me

**Comment by dineshrboson** [comment]
![Screenshot from 2022-01-17 16-27-03](https://user-images.githubusercontent.com/77951479/149757440-c4ccb0f4-03ba-43c0-864f-2cf0f3fa0e37.png)

**Comment by dineshrboson** [comment]
what was this error?

**Comment by dineshrboson** [comment]
c++ code is very inconsistent and its not executing every time
may be I will go with python can you help me with the formulae that you implemented to calculate IMU in that code I will try to replicate that in python

**Comment by pietrocolombo** [comment]
> what was this error?

You must first launch the program on the computer and then press the button at the bottom left of the phone.

Because initially, it sends you the input configuration

**Comment by pietrocolombo** [comment]
> hye finally its working for me

What was the problem in the end?
