### ISSUE TITLE
Potential vulnerability: topic name from ROS parameters

### ISSUE THREAD

**Issue by tandf** [pietrocolombo/imu_from_ios_sensorlog#4]
Hi,

We notice that you are using topic name from ROS parameters at the following locations:
https://github.com/pietrocolombo/imu_from_ios_sensorlog/blob/870e8519f4feb007bc68affdb8aad04ece6e094f/src/imu_from_ios_sensorlog_node.cpp#L39 
For security reasons detailed below, we strongly suggest avoiding the usage of strings from parameters as topic names.

Although parameters are usually set in parameter files, they can also be changed by nodes. Specifically, other nodes in the same ROS application can also change the parameters listed above before it’s used, either by accident or *intentionally* (i.e., by potential attackers). If the `/topic` parameter is changed, the `imu_from_ios_sensorlog_node` will attempt to publish IMU data to a wrong topic, and the downstream application such as robot_localization cannot receive IMU data. If an attacker exists, she can even launch a man-in-the-middle attack by first fooling the node to publish to another topic, e.g. to `/imu_iphone_fake`, and then forwarding all the data from `/imu_iphone_fake` to `/imu_iphone` after modifying the contents. The downstream application will receive maliciously modified IMU data, which may cause the robot to move dangerously and even crash into obstacles. Because ROS is an OSS (open-source software) community, third-party nodes are widely used in ROS applications, usually without complete vetting of their behavior, which gives the opportunity to potentially malicious actors to inject malicious code (e.g, by submitting hypocrite commits like in other OSS systems [1]) to infiltrate the ROS applications that use it (or software supply chain attacks, one of the primary means for real-world attackers today [2]).

We understand that using parameters to set topic names brings flexibility. Still, for the purpose of security, we strongly suggest that you avoid such vulnerable programming patterns if possible. For example, to avoid the exposure of this specific vulnerability, you may consider alternatives like remapping, which is designed for configuring names when launching the nodes.

[1] Q. Wu and K. Lu, “On the feasibility of stealthily introducing vulnerabilities in open-source software via hypocrite commits,” 2021, https://linuxreviews.org/images/d/d9/OpenSourceInsecurity.pdf.
[2] Supply chain attacks are the hacker’s new favourite weapon. and the threat is getting bigger. https://www.zdnet.com/article/supply-chain-attacks-are-the-hackers-new-favourite-weapon-and-the-threat-is-getting-bigger/.

**Comment by tandf** [comment]
Hi there, I wanted to follow up on this security vulnerability. Could you please let me know if there have been any updates or concerns regarding this issue? Thanks

**Comment by pietrocolombo** [comment]
No, there are no updates. But if you want to propose a solution with a pull request you are welcome.

**Comment by tandf** [comment]
Thank you for your reply. I just created a pull request #5 trying to address this problem. Please take a look when you have time.

**Comment by tandf** [comment]
@pietrocolombo Hello, I previously submitted a pull request. Would you mind taking a moment to review it when you have some time? I would greatly appreciate your feedback. Thank you!

**Comment by pietrocolombo** [comment]
Done, thank you
